-- MySQL Script generated by MySQL Workbench
-- Dom 12 Fev 2017 23:33:09 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema atividades_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atividades_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividades_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mysql
-- -----------------------------------------------------
-- This schema was created for a stub table
USE `atividades_db` ;

-- -----------------------------------------------------
-- Table `atividades_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividades_db`.`status` (
  `id` INT NOT NULL,
  `nome` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `atividades_db`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividades_db`.`atividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idstatus` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(600) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL,
  `situacao` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `atv_idstatus_fk_idx` (`idstatus` ASC),
  CONSTRAINT `atv_idstatus_fk`
    FOREIGN KEY (`idstatus`)
    REFERENCES `atividades_db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `atividades_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `atividades_db`.`vw_atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atividades_db`.`vw_atividades` (`id` INT, `idstatus` INT, `nome` INT, `descricao` INT, `data_inicio` INT, `data_fim` INT, `situacao` INT, `status` INT, `situacao_nome` INT);

-- -----------------------------------------------------
-- View `atividades_db`.`vw_atividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atividades_db`.`vw_atividades`;
USE `atividades_db`;
CREATE  OR REPLACE VIEW vw_atividades AS
SELECT a.*, s.nome as status,
	CASE a.situacao
		WHEN '0' THEN 'INATIVO'
        WHEN '1' THEN 'ATIVO'
        ELSE 'DESCONHECIDO'
	END as situacao_nome
FROM atividades a
INNER JOIN `status` s
ON a.idstatus = s.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `atividades_db`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `atividades_db`;
INSERT INTO `atividades_db`.`status` (`id`, `nome`) VALUES (1, 'Pendente');
INSERT INTO `atividades_db`.`status` (`id`, `nome`) VALUES (2, 'Em Desenvolvimento');
INSERT INTO `atividades_db`.`status` (`id`, `nome`) VALUES (3, 'Em Teste');
INSERT INTO `atividades_db`.`status` (`id`, `nome`) VALUES (4, 'Concluido');

COMMIT;

